<?php

require_once( config_get( 'class_path' ) . 'MantisPlugin.class.php' );

class PiwikPlugin extends MantisPlugin  {
	/**
	 *  A method that populates the plugin information and minimum requirements.
	 */
	function register() {
		$this->name = 'Piwik';
		$this->description = plugin_lang_get( 'description' );
		$this->version = '1.0';
		$this->requires = array(
			'MantisCore' => '1.2.0',
		);
		$this->page = 'config';
		$this->author = 'Johan Guilbaud';
		$this->contact = 'support@lapinkiller.fr';
		$this->url = 'http://www.lapinkiller.fr';
	}
	
	/**
	 * Default plugin configuration.
	 */
	function config() {
		return array(	"piwikUrl" => "mypiwik.fr",
						"idSite" => "1",
					);
	}


	function init(){
		return true;
	}
	
	function hooks() {
		$hooks = array(
			'EVENT_LAYOUT_BODY_END' => 'addPiwikJsCode',
			'EVENT_CORE_READY' 		=> 'prepareHeaders',
		);
		return $hooks;
	}


	function addPiwikJsCode(){		
		echo "<!-- Piwik code generated by Piwik Mantis Plugin-->
				<script type=\"text/javascript\">
					var pkBaseURL = ((\"https:\" == document.location.protocol) ? \"https://".plugin_config_get('piwikUrl')."/\" : \"http://".plugin_config_get('piwikUrl')."/\");
					document.write(unescape(\"%3Cscript src='\" + pkBaseURL + \"piwik.js' type='text/javascript'%3E%3C/script%3E\"));
				</script><script type=\"text/javascript\">
					try {
						var piwikTracker = Piwik.getTracker(pkBaseURL + \"piwik.php\", ".plugin_config_get('idSite').");
						piwikTracker.trackPageView();
						piwikTracker.enableLinkTracking();
					} catch( err ) {}
				</script><noscript>
				
				<img src=\"http://".plugin_config_get('piwikUrl')."/piwik.php?idsite=".plugin_config_get('idSite')."\" style=\"border:0\" alt=\"\" />
				</noscript>
			<!-- End Piwik Tracking Tag -->";
	}
	
	
	/**
	 * L'envoi d'une requête sur un site externe doit être autorisé via les headers http !
	 */
	function prepareHeaders(){
		
		foreach(headers_list() as $header){
			if(strpos($header, "X-Content-Security-Policy:") === 0){
				$header = str_replace("allow 'self';", "allow 'self' ".plugin_config_get('piwikUrl').";",$header);
				header($header);
				break;
			}
			
		}
	}
}